ignore:
  # We can make rules to match just by vulnerability ID:
  - vulnerability: CVE-2019-14697
  - vulnerability: CVE-2021-45046
  - vulnerability: CVE-2021-44228
  - vulnerability: CVE-2021-23463
  - vulnerability: CVE-2021-23463
  - vulnerability: CVE-2021-42392
  - vulnerability: GHSA-45hx-wfhj-473x
  - vulnerability: CVE-2022-23221
  - vulnerability: GHSA-h376-j262-vhq6
  - vulnerability: CVE-2019-12900
  - vulnerability: CVE-2021-3711
  - vulnerability: CVE-2021-3711
  - vulnerability: GHSA-7rjr-3q55-vv33
  - vulnerability: CVE-2021-45046
  - vulnerability: CVE-2021-44228
  - vulnerability: GHSA-jfh8-c2jp-5v3q
  - vulnerability: CVE-2019-20445
  - vulnerability: CVE-2019-20444
  - vulnerability: GHSA-6v73-fgf6-w5j7
  - vulnerability: CVE-2022-22965
  - vulnerability: CVE-2019-8457
  - vulnerability: CVE-2019-19646
  - vulnerability: CVE-2020-11656
  - vulnerability: CVE-2021-23926
  - vulnerability: GHSA-mw3r-pfmg-xp92
  - vulnerability: CVE-2021-26291
  - vulnerability: CVE-2022-28391
  - vulnerability: CVE-2022-28391
  - vulnerability: CVE-2016-1000027
